export enum AccountType {
  BANK = 'BANK',
  CASH = 'CASH',
  UPI = 'UPI',
  EWALLET = 'EWALLET',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  INVESTMENT = 'INVESTMENT',
  SAVINGS = 'SAVINGS',
}
